In [1]:
import pandas as pd
import numpy as np

In [2]:
from fastai.script import *
from fastai.vision import *
from fastai.callbacks import *
from fastai.distributed import *
from fastprogress import fastprogress
from torchvision.models import *

In [3]:
np.random.seed(42)

In [4]:
src = (ImageList.from_folder(path='train-snakes-cropped').split_by_rand_pct(0.2).label_from_folder())

In [5]:
data = (src.transform(size=32, resize_method=ResizeMethod.SQUISH)
        .databunch(bs=4).normalize())

In [6]:
df_classes = pd.read_csv('class.csv',low_memory=False)

In [7]:
df_classes.head()

original_class  class_idx
0  thamnophis_proximus          4
1      nerodia_sipedon         67
2   opheodrys_vernalis         72
3    crotalus_horridus         78
4     crotalus_pyrrhus        128

In [8]:
data_dict = df_classes.set_index('class_idx')['original_class'].to_dict()

In [9]:
df = pd.read_csv('temp.csv',low_memory=False)

In [10]:
df.head()

9.710495942272245884e-04  4.560796543955802917e-03  \
0                  0.006791                  0.007201   
1                  0.034093                  0.004136   
2                  0.001000                  0.000752   
3                  0.001125                  0.001070   
4                  0.000250                  0.000361   

   3.636183682829141617e-03  2.321038097143173218e-01  \
0                  0.006184                  0.004471   
1                  0.005501                  0.147228   
2                  0.000521                  0.000666   
3                  0.001788                  0.002591   
4                  0.001194                  0.000065   

   9.845637716352939606e-03  7.819023914635181427e-03  \
0                  0.008256                  0.004930   
1                  0.001751                  0.005609   
2                  0.008242                  0.000921   
3                  0.001593                  0.001903   
4                  0.965316                  0.000680   

   4.251129459589719772e-03  2.384667517617344856e-03  \
0                  0.006112                  0.004334   
1                  0.004705                  0.005269   
2                  0.001345                  0.000606   
3                  0.001439                  0.002392   
4                  0.001533                  0.000230   

   6.954384036362171173e-03  2.598663326352834702e-03  ...  \
0                  0.004334                  0.005289  ...   
1                  0.001835                  0.001620  ...   
2                  0.001178                  0.000886  ...   
3                  0.001673                  0.001892  ...   
4                  0.001121                  0.000547  ...   

   5.960918962955474854e-02  2.120967255905270576e-03  \
0                  0.003855                  0.005586   
1                  0.654457                  0.004267   
2                  0.001215                  0.001178   
3                  0.000761                  0.001827   
4                  0.001079                  0.000490   

   3.014502115547657013e-03  4.088271409273147583e-03  \
0                  0.006871                  0.006380   
1                  0.005458                  0.002499   
2                  0.000653                  0.001073   
3                  0.001526                  0.927955   
4                  0.000342                  0.000443   

   9.485552436672151089e-04  2.460364950820803642e-03  \
0                  0.004283                  0.005608   
1                  0.003962                  0.005787   
2                  0.006886                  0.000503   
3                  0.001750                  0.001336   
4                  0.001005                  0.000110   

   2.518710913136601448e-03  1.023784372955560684e-02  \
0                  0.006232                  0.005457   
1                  0.002799                  0.002357   
2                  0.001274                  0.000342   
3                  0.002078                  0.001423   
4                  0.000207                  0.000922   

   4.455145448446273804e-03.1  3.234088653698563576e-03  
0                    0.004949                  0.003736  
1                    0.003442                  0.001030  
2                    0.000717                  0.000165  
3                    0.001152                  0.001870  
4                    0.000275                  0.002393  

[5 rows x 45 columns]

In [11]:
df_y = pd.read_csv('temp_actual.csv',low_memory=False)

In [12]:
df_y.head()

1.900000000000000000e+01
0                      33.0
1                      35.0
2                      12.0
3                      38.0
4                       4.0

In [13]:
data.valid_ds.y.items

array([19, 33, 35, 12, ..., 22, 11, 29, 22])

In [14]:
df_y.head()

1.900000000000000000e+01
0                      33.0
1                      35.0
2                      12.0
3                      38.0
4                       4.0

In [15]:
data.classes[33]

'class-72'

In [21]:
len(df)

16482

In [27]:
count=0

In [134]:
y_pred = []

In [136]:
for i,row in df.iterrows():
    temp = np.asarray(row[:])
    y_pred.append(np.argmax(temp))
    
    if np.argmax(temp) == df_y.iloc[i,0]:
        print("Yes")
        count+=1

Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes


Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes


Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes


Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes


Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes


Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes


In [137]:
count

12590

In [138]:
count/len(df)

0.7638636087853415

In [44]:
import sklearn

In [175]:
y_true = np.asarray(df_y.iloc[:,0])

In [176]:
y_true

array([33., 35., 12., 38., ..., 22., 11., 29., 22.])

In [48]:
y_pred = np.asarray(y_pred)

In [49]:
y_pred

array([33, 35, 12, 38, ..., 22, 11, 29, 22])

In [50]:
assert len(y_pred) == len(y_true)

In [52]:
import sklearn.metrics


In [140]:
sklearn.metrics.accuracy_score(y_true,y_pred)

0.7638636087853415

In [139]:
sklearn.metrics.f1_score(y_true,y_pred,average='macro')

0.7247040631915644

In [59]:
data.classes[0],data.classes[35]

('class-1059', 'class-771')

In [279]:
y_pred=[]

In [280]:
count=0
changed=0

In [281]:
for i,row in df.iterrows():
    temp = np.asarray(row[:])
    max_temp =np.argmax(temp)
    if max_temp  == 35:
        if temp[0] > 0.1:
            changed += 1
            y_pred.append(0)
        else:
            y_pred.append(35)
    else:
        y_pred.append(np.argmax(temp))

    

In [282]:
y_true = df_y.iloc[:,0]

In [283]:
y_true_list  = y_true.tolist()

In [284]:
count,changed

(0, 76)

In [285]:
sklearn.metrics.accuracy_score(y_true,y_pred)

0.762528819318044

In [286]:
sklearn.metrics.f1_score(y_true,y_pred,average='macro')

0.7254788367057878

In [111]:
count,changed

(0, 23)

In [88]:
len(y_true[y_true==0])

170

In [89]:
y_pred = np.asarray(y_pred)

In [90]:
len(y_pred[y_pred==0])

116

In [91]:
data.classes[0]

'class-1059'

In [94]:
temp[0]

0.001223979750648141

In [178]:
temp_dict={'class-1059': 0.010786609558707548,
 'class-128': 0.00907579746896878,
 'class-140': 0.018127328099785237,
 'class-1625': 0.020335610371646627,
 'class-204': 0.1343776162684883,
 'class-239': 0.008202191295485155,
 'class-273': 0.007037383064173654,
 'class-326': 0.007728987951514857,
 'class-337': 0.04211509761335647,
 'class-362': 0.02606258417559484,
 'class-390': 0.027809796522562092,
 'class-394': 0.01492410546367861,
 'class-4': 0.0181394615188614,
 'class-448': 0.031122219930354175,
 'class-450': 0.01212128565708531,
 'class-460': 0.016889719354016768,
 'class-508': 0.024970576458740307,
 'class-526': 0.007619787179829404,
 'class-536': 0.016525716781731925,
 'class-540': 0.012764356868121869,
 'class-543': 0.01671985148695051,
 'class-561': 0.00643071211036558,
 'class-581': 0.023114163340087604,
 'class-597': 0.012181952752466118,
 'class-629': 0.0063943118531370954,
 'class-635': 0.014378101605251345,
 'class-639': 0.026438720166955847,
 'class-653': 0.008663261220379291,
 'class-654': 0.012970624992416612,
 'class-663': 0.011587415217734206,
 'class-67': 0.03879054078648823,
 'class-697': 0.05591079510295206,
 'class-707': 0.013917031680357208,
 'class-72': 0.01030127279566109,
 'class-734': 0.007195117512163752,
 'class-771': 0.0668915393668782,
 'class-78': 0.025916983146680905,
 'class-784': 0.006272977662375481,
 'class-804': 0.03092808522513559,
 'class-811': 0.011017144521154616,
 'class-854': 0.021488285183881965,
 'class-857': 0.013722896975138624,
 'class-872': 0.06694007304318284,
 'class-957': 0.007280051445696883,
 'class-966': 0.01781185920380504}


In [179]:
y_true

array([33., 35., 12., 38., ..., 22., 11., 29., 22.])

In [182]:
temp_dict[data.classes[0]]

0.010786609558707548

In [199]:
sum=0

In [200]:
for c in range(data.c):
    sum_temp = np.round(temp_dict[data.classes[c]] * len(y_true))
    sum += sum_temp
    

NameError: name 'probs_np' is not defined

In [248]:
sum

16484.0